# Assign normally distributed values to the spectra for each brick group

Assign a range of normally distributed values for brick properties to the spectra.

12 brick groups, since Group 1 is divided into A, B, C and D type.

In [1]:
# Imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import hoggorm as ho
import hoggormplot as hopl
np.bool = np.bool_
from scipy import stats
from sklearn.preprocessing import StandardScaler
from matplotlib.axes import Axes
from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import confusion_matrix

C:\Users\marth\anaconda3\envs\inf200\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\marth\anaconda3\envs\inf200\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (
C:\Users\marth\AppData\Local\Temp/ipykernel_18240/3640070234.py:4: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
# from untreated brick, no mortar removal
spectral = pd.read_excel(r'C:\Users\marth\OneDrive\Skole\Master\Kode\murstein-master-2024\Streamline v2\Resultater 2\snv\excel\All Bricks Mean Spectra after SNV ABCD.xlsx')
#from dried brick with SNV, no mortar removal, split in ABBCD
#spectral = pd.read_excel(r"C:\Users\marth\OneDrive\Skole\Master\Kode\murstein-master-2024\Streamline v2\Resultater 2\dried spectra\dried mean snv spectra\excel\All Dried Bricks Mean Spectra after SNV ABCD.xlsx")

# from untreated brick with mortar removal
#spectral = pd.read_excel(r"C:\Users\marth\OneDrive\Skole\Master\Kode\murstein-master-2024\Streamline v3 edge and mortar removal\spectra after mortar removal\snv spectra\excel\All bricks no mortar SNV.xlsx")

# from untreated brick with mortar removal for ABCD split 

#spectral = pd.read_excel(r"C:\Users\marth\OneDrive\Skole\Master\Kode\murstein-master-2024\Streamline v3 edge and mortar removal\spectra after mortar removal\snv spectra\excel\All bricks no mortar SNV ABCD.xlsx")
#spectral

# from dried brick with mortar removal for ABCD split
#spectral = pd.read_excel(r"C:\Users\marth\OneDrive\Skole\Master\Kode\murstein-master-2024\Streamline v3 edge and mortar removal\spectra after mortar removal\dried snv spectra\excel\All dried bricks no mortar SNV ABCD.xlsx")
spectral

,Unnamed: 0,953,959,964,970,975,981,986,991,997,...,2478,2483,2489,2494,2499,2505,2510,2516,group,brick_id
0,0,-1.113136,-1.099415,-1.085676,-1.073993,-1.064066,-1.058398,-1.052575,-1.046339,-1.039202,...,1.663515,1.726639,1.780660,1.821972,1.849622,1.859123,1.863208,1.867295,1,A4_A
1,1,-2.175014,-2.136737,-2.098319,-2.061720,-2.029290,-2.000825,-1.973227,-1.944938,-1.917341,...,1.071645,1.106687,1.132426,1.144199,1.137728,1.111032,1.073438,1.035979,1,A4_A
2,2,-2.587283,-2.539374,-2.491245,-2.444833,-2.403979,-2.367284,-2.331161,-2.295283,-2.258954,...,0.791275,0.809937,0.823247,0.826766,0.812304,0.781435,0.743765,0.706230,1,A4_A
3,3,-2.189144,-2.158043,-2.126853,-2.097751,-2.070422,-2.048163,-2.025966,-2.003464,-1.980071,...,0.898399,0.930641,0.955737,0.971394,0.973327,0.962265,0.946508,0.930774,1,A4_A
4,4,-2.425842,-2.383028,-2.340041,-2.299257,-2.262290,-2.229124,-2.197027,-2.164672,-2.132360,...,1.007812,1.029363,1.043587,1.047702,1.033859,1.001383,0.959513,0.917808,1,A4_A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,1459,-0.376035,-0.374886,-0.373737,-0.374245,-0.378397,-0.384897,-0.392306,-0.398516,-0.404163,...,2.892272,2.958093,3.009169,3.042729,3.056715,3.054227,3.043716,3.033213,9,FV6_B
1460,1460,1.553917,1.524941,1.495989,1.463957,1.423202,1.373924,1.325594,1.278005,1.233912,...,1.510145,1.612959,1.701299,1.764643,1.798358,1.803767,1.796769,1.789772,9,FV6_B
1461,1461,0.040009,0.032494,0.024982,0.015723,0.004007,-0.013167,-0.027390,-0.042244,-0.056658,...,2.927709,2.998406,3.056017,3.098659,3.123458,3.127906,3.129172,3.130438,9,FV6_B
1462,1462,-0.423417,-0.430742,-0.438064,-0.447933,-0.461395,-0.478253,-0.495029,-0.510384,-0.524447,...,2.864448,2.929612,2.979723,3.009803,3.019046,3.008692,2.988783,2.968892,9,FV6_B
1463,1463,0.277330,0.244050,0.210788,0.170531,0.114999,0.044840,-0.022630,-0.090146,-0.149663,...,2.090771,2.191071,2.274007,2.322773,2.332551,2.295702,2.245369,2.195075,9,FV6_B

In [4]:
#labdata = pd.read_excel(r"C:\Users\marth\OneDrive\Skole\Master\Data\murstein_labdata_v3.xlsx")
labdata = pd.read_excel(r"C:\Users\marth\OneDrive\Skole\Master\Data\murstein_labdata_vABCD.xlsx")
labdata

,Project ID,Brick ID,Type,Length mm,Width mm,Height mm,Volume cm3,Dry density,Water absorption,PN,Minute suction,Max force kN,Compressive strength MPa,FR,Weight (group mean)
0,1,A1_1,M,221,106,66,1463,1920.000000,10.200000,0.720000,2.300000,406,17.3,0.568716,3.04
1,1,A2_1,M,221,106,66,1477,1950.000000,9.500000,0.710000,2.100000,523,22.3,0.527635,3.04
2,1,A3_1,M,221,111,66,1469,1938.000000,9.700000,0.720000,2.200000,513,21.9,0.551049,3.04
3,10,B1_1,M,233,113,61,1510,1882.000000,13.000000,0.990000,1.900000,1998,80.9,0.725091,3.04
4,10,B2_1,M,228,106,57,1324,2135.000000,6.800000,0.950000,1.100000,1945,80.5,0.466683,3.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,9,TP6,H,227,105,61,1077,2103.342618,7.323533,0.761708,0.847493,1571,66.0,0.333385,2.20
59,9,TP7,H,227,105,60,1015,2157.832512,6.711716,0.785256,0.537025,1202,50.0,0.266680,2.20
60,9,TP8,H,227,105,61,1015,2143.054187,7.006252,0.791688,0.654500,1623,68.0,0.298866,2.20
61,9,TP9,H,228,107,61,1024,2096.582031,7.457264,0.791790,0.573865,1178,48.0,0.286090,2.20
62,9,TP10,H,226,107,60,1048,2100.572519,7.586082,0.802885,0.686461,1416,59.0,0.316682,2.20

In [5]:
projectID = labdata.iloc[:, 0]
red_data = labdata.drop(labels=["Volume cm3", "Weight (group mean)", "Height mm", "Length mm", "Width mm"], axis=1)
int_data = red_data.iloc[:,3:]
int_data["group"] = projectID

int_data

,Dry density,Water absorption,PN,Minute suction,Max force kN,Compressive strength MPa,FR,group
0,1920.000000,10.200000,0.720000,2.300000,406,17.3,0.568716,1
1,1950.000000,9.500000,0.710000,2.100000,523,22.3,0.527635,1
2,1938.000000,9.700000,0.720000,2.200000,513,21.9,0.551049,1
3,1882.000000,13.000000,0.990000,1.900000,1998,80.9,0.725091,10
4,2135.000000,6.800000,0.950000,1.100000,1945,80.5,0.466683,10
...,...,...,...,...,...,...,...,...
58,2103.342618,7.323533,0.761708,0.847493,1571,66.0,0.333385,9
59,2157.832512,6.711716,0.785256,0.537025,1202,50.0,0.266680,9
60,2143.054187,7.006252,0.791688,0.654500,1623,68.0,0.298866,9
61,2096.582031,7.457264,0.791790,0.573865,1178,48.0,0.286090,9
62,2100.572519,7.586082,0.802885,0.686461,1416,59.0,0.316682,9

In [ ]:
# Find the STD values for each group
# make normal distributions for each proprty.

In [6]:
grouped_data = int_data.groupby("group").agg(['mean', 'std'])
grouped_data

       Dry density             Water absorption                  PN            \
              mean         std             mean       std      mean       std
group
1      1936.000000   15.099669         9.800000  0.360555  0.716667  0.005774
2      2123.700000   37.169432         8.000000  0.942809  0.910000  0.031623
3      2037.200000  139.634165         8.260000  3.888187  0.784000  0.074364
4      1948.276168   75.000152         9.999405  2.152508  0.709786  0.035544
5      2062.252018  121.371903         6.646186  2.779948  0.642642  0.081682
6      1810.085044  156.832957        15.948796  4.726035  0.928172  0.029523
7      1344.706608   43.061440        27.039464  1.487592  0.724873  0.017191
8      1588.435768   42.206720        17.699169  1.512340  0.777296  0.060302
9      2115.089535   22.123162         7.262387  0.309192  0.787249  0.019536
10     2037.000000  135.790279         9.300000  3.269557  0.973333  0.020817
11     1880.000000  116.073253        14.433333  3.330666  0.936667  0.030551
12     1842.333333  139.270720        16.133333  4.252450  0.956667  0.015275

      Minute suction           Max force kN              \
                mean       std         mean         std
group
1           2.200000  0.100000   480.666667   64.856251
2           0.850000  0.217307  2004.700000  353.836450
3           0.620000  0.491935  3016.000000   31.304952
4           2.145236  0.675175  1074.200000  321.128790
5           1.129777  0.721452  1377.600000  216.585549
6           3.049110  1.677667  1531.666667  438.928620
7           4.422496  1.182138   253.000000   23.515952
8           3.536093  2.142083   938.200000   91.300237
9           0.721674  0.159169  1446.100000  169.270625
10          1.366667  0.461880  2324.666667  612.276354
11          2.766667  1.193035  1516.000000  390.846517
12          2.300000  0.854400  1007.666667  203.689306

      Compressive strength MPa                   FR
                          mean        std      mean       std
group
1                    20.500000   2.778489  0.549133  0.020607
2                    88.320000  16.003319  0.391629  0.050070
3                   133.940000   4.105241  0.299507  0.166042
4                    44.400000  15.076472  0.535948  0.134317
5                    57.200000   9.497368  0.333823  0.165270
6                    55.000000  16.370706  0.884273  0.280544
7                     9.333333   0.577350  1.128938  0.178704
8                    35.900000   3.725289  0.887078  0.167634
9                    59.700000   7.103207  0.314295  0.032860
10                   94.266667  23.499007  0.560873  0.142729
11                   57.200000  18.038570  0.827426  0.259109
12                   37.566667   9.457449  0.789685  0.213368

In [7]:
grouped_data.to_csv('mean labdata ABCD.csv', index=True)

In [8]:
df1 = grouped_data.iloc[:, :6]
df1

       Dry density             Water absorption                  PN
              mean         std             mean       std      mean       std
group
1      1936.000000   15.099669         9.800000  0.360555  0.716667  0.005774
2      2123.700000   37.169432         8.000000  0.942809  0.910000  0.031623
3      2037.200000  139.634165         8.260000  3.888187  0.784000  0.074364
4      1948.276168   75.000152         9.999405  2.152508  0.709786  0.035544
5      2062.252018  121.371903         6.646186  2.779948  0.642642  0.081682
6      1810.085044  156.832957        15.948796  4.726035  0.928172  0.029523
7      1344.706608   43.061440        27.039464  1.487592  0.724873  0.017191
8      1588.435768   42.206720        17.699169  1.512340  0.777296  0.060302
9      2115.089535   22.123162         7.262387  0.309192  0.787249  0.019536
10     2037.000000  135.790279         9.300000  3.269557  0.973333  0.020817
11     1880.000000  116.073253        14.433333  3.330666  0.936667  0.030551
12     1842.333333  139.270720        16.133333  4.252450  0.956667  0.015275

In [9]:
# Saving for use in Appendix
df1.to_excel('three_first_ABCD.xlsx')

In [10]:
df2 = grouped_data.iloc[:, 6:10]
df2

      Minute suction           Max force kN
                mean       std         mean         std
group
1           2.200000  0.100000   480.666667   64.856251
2           0.850000  0.217307  2004.700000  353.836450
3           0.620000  0.491935  3016.000000   31.304952
4           2.145236  0.675175  1074.200000  321.128790
5           1.129777  0.721452  1377.600000  216.585549
6           3.049110  1.677667  1531.666667  438.928620
7           4.422496  1.182138   253.000000   23.515952
8           3.536093  2.142083   938.200000   91.300237
9           0.721674  0.159169  1446.100000  169.270625
10          1.366667  0.461880  2324.666667  612.276354
11          2.766667  1.193035  1516.000000  390.846517
12          2.300000  0.854400  1007.666667  203.689306

In [11]:
# Saving for use in Appendix
df2.to_excel('nextABCD.xlsx')

In [12]:
df3 = grouped_data.iloc[:, 10:]
df3

      Compressive strength MPa                   FR
                          mean        std      mean       std
group
1                    20.500000   2.778489  0.549133  0.020607
2                    88.320000  16.003319  0.391629  0.050070
3                   133.940000   4.105241  0.299507  0.166042
4                    44.400000  15.076472  0.535948  0.134317
5                    57.200000   9.497368  0.333823  0.165270
6                    55.000000  16.370706  0.884273  0.280544
7                     9.333333   0.577350  1.128938  0.178704
8                    35.900000   3.725289  0.887078  0.167634
9                    59.700000   7.103207  0.314295  0.032860
10                   94.266667  23.499007  0.560873  0.142729
11                   57.200000  18.038570  0.827426  0.259109
12                   37.566667   9.457449  0.789685  0.213368

In [13]:
# Saving for use in Appendix
df3.to_excel('lastABCD.xlsx')

## Make normaldistributions for each property and for each group

In [7]:

distributions = {}
for group in range(0, grouped_data.shape[0]):
    #print(group)
    for prop in range(0, len(grouped_data.columns), 2):
                  
       # print(group)
       # print(prop)
        distributions[f'{group+1}_{grouped_data.columns[prop]}'] = [grouped_data.iloc[group, prop], grouped_data.iloc[group, prop+1]]

distributions

{"1_('Dry density', 'mean')": [1936.0, 15.0996688705415],
 "1_('Water absorption', 'mean')": [9.799999999999999, 0.36055512754639857],
 "1_('PN', 'mean')": [0.7166666666666667, 0.0057735026918962545],
 "1_('Minute suction', 'mean')": [2.1999999999999997, 0.09999999999999998],
 "1_('Max force kN', 'mean')": [480.6666666666667, 64.8562513049693],
 "1_('Compressive strength MPa', 'mean')": [20.5, 2.77848879788996],
 "1_('FR', 'mean')": [0.5491330684549917, 0.020607351386845694],
 "2_('Dry density', 'mean')": [2123.7, 37.169431885175015],
 "2_('Water absorption', 'mean')": [8.0, 0.9428090415820634],
 "2_('PN', 'mean')": [0.9099999999999999, 0.03162277660168379],
 "2_('Minute suction', 'mean')": [0.85, 0.2173067468400883],
 "2_('Max force kN', 'mean')": [2004.7, 353.8364499784236],
 "2_('Compressive strength MPa', 'mean')": [88.32000000000001,
  16.003319100181137],
 "2_('FR', 'mean')": [0.3916289995943122, 0.05006999081943297],
 "3_('Dry density', 'mean')": [2037.2, 139.63416487378723],
 "3_('Water absorption', 'mean')": [8.26, 3.8881872382898433],
 "3_('PN', 'mean')": [0.784, 0.07436396977031282],
 "3_('Minute suction', 'mean')": [0.62, 0.49193495504995377],
 "3_('Max force kN', 'mean')": [3016.0, 31.304951684997057],
 "3_('Compressive strength MPa', 'mean')": [133.94, 4.105240553244096],
 "3_('FR', 'mean')": [0.29950715267996003, 0.16604234360754888],
 "4_('Dry density', 'mean')": [1948.2761676332357, 75.00015201546562],
 "4_('Water absorption', 'mean')": [9.999405347019474, 2.15250787331351],
 "4_('PN', 'mean')": [0.7097856609929304, 0.03554387141944542],
 "4_('Minute suction', 'mean')": [2.1452355613282856, 0.6751753763334475],
 "4_('Max force kN', 'mean')": [1074.2, 321.12879036299444],
 "4_('Compressive strength MPa', 'mean')": [44.4, 15.076471735787521],
 "4_('FR', 'mean')": [0.5359482961691432, 0.13431707448986635],
 "5_('Dry density', 'mean')": [2062.2520180248152, 121.37190316347579],
 "5_('Water absorption', 'mean')": [6.646186192961314, 2.7799477417889356],
 "5_('PN', 'mean')": [0.6426418366569158, 0.0816820094742593],
 "5_('Minute suction', 'mean')": [1.1297768351733013, 0.7214522382749706],
 "5_('Max force kN', 'mean')": [1377.6, 216.5855489177429],
 "5_('Compressive strength MPa', 'mean')": [57.2, 9.497368056467012],
 "5_('FR', 'mean')": [0.33382274740913986, 0.16526989868989608],
 "6_('Dry density', 'mean')": [1810.0850443900083, 156.83295697306048],
 "6_('Water absorption', 'mean')": [15.948796402087794, 4.72603518062613],
 "6_('PN', 'mean')": [0.9281717594245756, 0.029523161795441184],
 "6_('Minute suction', 'mean')": [3.049109881352018, 1.6776671870401407],
 "6_('Max force kN', 'mean')": [1531.6666666666667, 438.92861986128605],
 "6_('Compressive strength MPa', 'mean')": [55.0, 16.3707055437449],
 "6_('FR', 'mean')": [0.8842725262981334, 0.2805436220142597],
 "7_('Dry density', 'mean')": [1344.7066084650753, 43.0614401976017],
 "7_('Water absorption', 'mean')": [27.03946424853577, 1.4875923287585868],
 "7_('PN', 'mean')": [0.7248731293728436, 0.017191229797544623],
 "7_('Minute suction', 'mean')": [4.422496286491152, 1.182137975909851],
 "7_('Max force kN', 'mean')": [253.0, 23.515952032609693],
 "7_('Compressive strength MPa', 'mean')": [9.333333333333334,
  0.5773502691896258],
 "7_('FR', 'mean')": [1.1289378977666937, 0.17870360581903946],
 "8_('Dry density', 'mean')": [1588.4357683052258, 42.20671954195751],
 "8_('Water absorption', 'mean')": [17.69916932525208, 1.5123400187592129],
 "8_('PN', 'mean')": [0.7772963282529063, 0.0603015634901754],
 "8_('Minute suction', 'mean')": [3.536092746235171, 2.1420829917506787],
 "8_('Max force kN', 'mean')": [938.2, 91.30023731257951],
 "8_('Compressive strength MPa', 'mean')": [35.9, 3.7252889522529364],
 "8_('FR', 'mean')": [0.8870782072534036, 0.1676340443871489],
 "9_('Dry density', 'mean')": [2115.0895352924376, 22.12316195060974],
 "9_('Water absorption', 'mean')": [7.262386667824501, 0.3091920600402939],
 "9_('PN', 'mean')": [0.7872485335164574, 0.019536172191787056],
 "9_('Minute suction', 'mean')": [0.7216738873304641, 0.15916913784802555],
 "9_('Max force kN', 'mean')": [1446.1, 169.27062487166648],
 "9_('Compressive strength MPa', 'mean')": [59.7, 7.103207413243369],
 "9_('FR', 'mean')": [0.31429494705895367, 0.032860399870152164],
 "10_('Dry density', 'mean')": [2037.0, 135.79027947537335],
 "10_('Water absorption', 'mean')": [9.299999999999999, 3.2695565448543635],
 "10_('PN', 'mean')": [0.9733333333333333, 0.02081665999466135],
 "10_('Minute suction', 'mean')": [1.3666666666666665, 0.4618802153517005],
 "10_('Max force kN', 'mean')": [2324.6666666666665, 612.2763537270841],
 "10_('Compressive strength MPa', 'mean')": [94.26666666666667,
  23.49900707122183],
 "10_('FR', 'mean')": [0.5608734701540451, 0.1427286199417768],
 "11_('Dry density', 'mean')": [1880.0, 116.07325273291862],
 "11_('Water absorption', 'mean')": [14.433333333333332, 3.330665599145813],
 "11_('PN', 'mean')": [0.9366666666666666, 0.030550504633038857],
 "11_('Minute suction', 'mean')": [2.766666666666667, 1.1930353445448854],
 "11_('Max force kN', 'mean')": [1516.0, 390.8465171905719],
 "11_('Compressive strength MPa', 'mean')": [57.199999999999996,
  18.03856978809573],
 "11_('FR', 'mean')": [0.8274264918030725, 0.25910942600559117],
 "12_('Dry density', 'mean')": [1842.3333333333333, 139.27071958359852],
 "12_('Water absorption', 'mean')": [16.133333333333336, 4.252450274057692],
 "12_('PN', 'mean')": [0.9566666666666667, 0.015275252316519468],
 "12_('Minute suction', 'mean')": [2.3000000000000003, 0.8544003745317532],
 "12_('Max force kN', 'mean')": [1007.6666666666666, 203.68930588848627],
 "12_('Compressive strength MPa', 'mean')": [37.56666666666666,
  9.457448563610235],
 "12_('FR', 'mean')": [0.789685219935755, 0.2133682891877233]}

In [8]:
# Make normaldistributions from each element in the dictionary 
columns = ['Dry density', "Water absorption", 'PN', 'Minute suction', 'Max force', "Compressive strength", 'FR']
groups = [1,2,3,4,5,6,7,8,9, 10, 11, 12] # DENNE MÅ ENDRES MTP GRUPPESTØRRELSE
normal_dists = {}

In [8]:
list(distributions.keys())

["1_('Dry density', 'mean')",
 "1_('Water absorption', 'mean')",
 "1_('PN', 'mean')",
 "1_('Minute suction', 'mean')",
 "1_('Max force kN', 'mean')",
 "1_('Compressive strength MPa', 'mean')",
 "1_('FR', 'mean')",
 "2_('Dry density', 'mean')",
 "2_('Water absorption', 'mean')",
 "2_('PN', 'mean')",
 "2_('Minute suction', 'mean')",
 "2_('Max force kN', 'mean')",
 "2_('Compressive strength MPa', 'mean')",
 "2_('FR', 'mean')",
 "3_('Dry density', 'mean')",
 "3_('Water absorption', 'mean')",
 "3_('PN', 'mean')",
 "3_('Minute suction', 'mean')",
 "3_('Max force kN', 'mean')",
 "3_('Compressive strength MPa', 'mean')",
 "3_('FR', 'mean')",
 "4_('Dry density', 'mean')",
 "4_('Water absorption', 'mean')",
 "4_('PN', 'mean')",
 "4_('Minute suction', 'mean')",
 "4_('Max force kN', 'mean')",
 "4_('Compressive strength MPa', 'mean')",
 "4_('FR', 'mean')",
 "5_('Dry density', 'mean')",
 "5_('Water absorption', 'mean')",
 "5_('PN', 'mean')",
 "5_('Minute suction', 'mean')",
 "5_('Max force kN', 'mean')",
 "5_('Compressive strength MPa', 'mean')",
 "5_('FR', 'mean')",
 "6_('Dry density', 'mean')",
 "6_('Water absorption', 'mean')",
 "6_('PN', 'mean')",
 "6_('Minute suction', 'mean')",
 "6_('Max force kN', 'mean')",
 "6_('Compressive strength MPa', 'mean')",
 "6_('FR', 'mean')",
 "7_('Dry density', 'mean')",
 "7_('Water absorption', 'mean')",
 "7_('PN', 'mean')",
 "7_('Minute suction', 'mean')",
 "7_('Max force kN', 'mean')",
 "7_('Compressive strength MPa', 'mean')",
 "7_('FR', 'mean')",
 "8_('Dry density', 'mean')",
 "8_('Water absorption', 'mean')",
 "8_('PN', 'mean')",
 "8_('Minute suction', 'mean')",
 "8_('Max force kN', 'mean')",
 "8_('Compressive strength MPa', 'mean')",
 "8_('FR', 'mean')",
 "9_('Dry density', 'mean')",
 "9_('Water absorption', 'mean')",
 "9_('PN', 'mean')",
 "9_('Minute suction', 'mean')",
 "9_('Max force kN', 'mean')",
 "9_('Compressive strength MPa', 'mean')",
 "9_('FR', 'mean')",
 "10_('Dry density', 'mean')",
 "10_('Water absorption', 'mean')",
 "10_('PN', 'mean')",
 "10_('Minute suction', 'mean')",
 "10_('Max force kN', 'mean')",
 "10_('Compressive strength MPa', 'mean')",
 "10_('FR', 'mean')",
 "11_('Dry density', 'mean')",
 "11_('Water absorption', 'mean')",
 "11_('PN', 'mean')",
 "11_('Minute suction', 'mean')",
 "11_('Max force kN', 'mean')",
 "11_('Compressive strength MPa', 'mean')",
 "11_('FR', 'mean')",
 "12_('Dry density', 'mean')",
 "12_('Water absorption', 'mean')",
 "12_('PN', 'mean')",
 "12_('Minute suction', 'mean')",
 "12_('Max force kN', 'mean')",
 "12_('Compressive strength MPa', 'mean')",
 "12_('FR', 'mean')"]

In [9]:
# Eks på tilegning av verdier fra normal distribusjon. Her kun en per verdi per gruppe. 

key_list = list(distributions.keys())
counter = 0
for g in range(len(groups)):
    #print(g)
    for col in range(len(columns)):
        #print(col)
        #print(counter)
        key = key_list[counter]
        #print(key)
        #print(distributions[key][0])
        #print(distributions[key][1])
        normal_dists[f'{groups[g]}_{columns[col]}'] = np.random.normal(distributions[key][0], distributions[key][1], 1) 
        counter += 1
#normal_dists       

# er hvertfall 120 spektre per gruppe, hvis det er 10 stein i en gruppe. Så trenger minst 120 normaldistribusjoner. 
# går det an å tilegne spektrene direkte, med np.random.normal(distributions[key][0], distributions[key][1], 1)? Ja forskjellig hver gang.

In [ ]:
# regne ut FR basert på egenskapene som blir lagd!
# Bruker poretall, tørrtetthet og minuttsug

In [46]:
spectral

,Unnamed: 0,953,959,964,970,975,981,986,991,997,...,2478,2483,2489,2494,2499,2505,2510,2516,group,brick_id
0,0,4.564952,4.425837,4.288240,4.148088,4.004263,3.854006,3.702563,3.548011,3.394499,...,0.632243,0.681713,0.728757,0.775475,0.822141,0.869620,0.918052,0.966670,1,A9_B
1,1,4.166178,4.042790,3.920336,3.794294,3.662620,3.523419,3.380742,3.235313,3.089030,...,1.424914,1.493582,1.554828,1.610352,1.660244,1.706270,1.750145,1.794138,1,A9_B
2,2,4.365933,4.235829,4.106800,3.974876,3.837642,3.694337,3.547977,3.399301,3.250602,...,1.090652,1.151935,1.208206,1.260416,1.310409,1.358614,1.405342,1.452210,1,A9_B
3,3,4.475484,4.347092,4.219944,4.089712,3.955436,3.814415,3.671810,3.525949,3.380619,...,0.639994,0.691965,0.741062,0.789697,0.837400,0.885350,0.934352,0.983538,1,A9_B
4,4,4.167475,4.054071,3.941422,3.824565,3.701470,3.570901,3.436358,3.298501,3.159665,...,1.293840,1.361641,1.422207,1.477998,1.527884,1.573978,1.617804,1.661744,1,A9_B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,1459,0.925933,0.812140,0.698517,0.582075,0.465935,0.350932,0.245844,0.142975,0.050000,...,0.686323,0.809542,0.919913,1.001033,1.046276,1.055649,1.042150,1.028653,9,FV6_A
1460,1460,3.605123,3.481163,3.357489,3.231244,3.094204,2.946122,2.796618,2.651848,2.509309,...,0.153880,0.221076,0.277366,0.307393,0.308711,0.279292,0.239207,0.199152,9,FV6_A
1461,1461,1.040879,0.971682,0.902594,0.830338,0.767414,0.704992,0.646425,0.587726,0.537312,...,0.427887,0.527364,0.614296,0.691433,0.758254,0.819376,0.883741,0.948201,9,FV6_A
1462,1462,1.085196,1.012857,0.940619,0.867648,0.794280,0.720073,0.652334,0.587969,0.528217,...,0.380081,0.482569,0.573779,0.642628,0.685239,0.708016,0.719662,0.731310,9,FV6_A
1463,1463,0.479341,0.380265,0.281325,0.187129,0.088557,-0.023537,-0.127706,-0.226993,-0.322403,...,2.189796,2.274457,2.342873,2.359492,2.343938,2.263831,2.171281,2.078849,9,FV6_A

In [10]:
# Tilegne hvert spekter en verdi for alle egenskapene
spectral = spectral.iloc[:, 1:]

In [11]:
dry_density = []
water_abs = []
pn = []
min_suction = []
max_f = []
comp_strength = []
fr = []

# Distributions contains the mean value and std for all proprties for all groups
columns = ['Dry density', "Water absorption", 'PN', 'Minute suction', 'Max force kN', "Compressive strength MPa", 'FR']
#key_list = list(distributions.keys())
#counter = 0
for g in spectral['group']:
    # g er lik 1 
    #print(g)
    for col in range(len(columns)):
        #print(col)
        mean_std = distributions[f"{g}_('{columns[col]}', 'mean')"]
        if col == 0:
            value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            while value < 0:
                value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            dry_density.append(value)
        elif col == 1:
            value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            while value < 0:
                value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            water_abs.append(value)
        elif col == 2:
            value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            while value < 0:
                value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            pn.append(value)
        elif col == 3:
            value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            while value < 0:
                value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            min_suction.append(value)       
        elif col == 4:
            value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            while value < 0:
                value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            max_f.append(value)   
        elif col == 5:
            value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            while value < 0:
                value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            comp_strength.append(value)
        elif col == 6:
            value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            while value < 0:
                value = np.random.normal(mean_std[0], mean_std[1], 1)[0]
            fr.append(value) 
        #normal_dists[f'{groups[g]}_{columns[col]}'] = np.random.normal(distributions[key][0], distributions[key][1], 1) 
        #counter += 1
        else:
            raise ValueError("something wrong during iteration")

In [49]:
len(dry_density)

1464

In [12]:
# Add the columns to spectral as a dataframe
spectral['Dry density'] = dry_density
spectral['Water absorption'] = water_abs
spectral['PN'] = pn
spectral['Minute suction'] = min_suction
spectral['Max force kN'] = max_f
spectral['Compressive strength MPa'] = comp_strength
spectral['FR'] = fr
spectral['FR calculated'] = (1000*(spectral['Minute suction']**0.5)*spectral['PN'])/spectral['Dry density']

spectral

,953,959,964,970,975,981,986,991,997,1002,...,group,brick_id,Dry density,Water absorption,PN,Minute suction,Max force kN,Compressive strength MPa,FR,FR calculated
0,-1.113136,-1.099415,-1.085676,-1.073993,-1.064066,-1.058398,-1.052575,-1.046339,-1.039202,-1.031346,...,1,A4_A,1938.555948,9.844090,0.713352,2.225772,410.482537,25.290245,0.542385,0.548992
1,-2.175014,-2.136737,-2.098319,-2.061720,-2.029290,-2.000825,-1.973227,-1.944938,-1.917341,-1.888467,...,1,A4_A,1915.847524,9.712062,0.716514,2.202328,453.973249,17.236979,0.520962,0.555015
2,-2.587283,-2.539374,-2.491245,-2.444833,-2.403979,-2.367284,-2.331161,-2.295283,-2.258954,-2.222399,...,1,A4_A,1954.625364,9.926878,0.719688,2.179473,510.902357,20.578115,0.553357,0.543571
3,-2.189144,-2.158043,-2.126853,-2.097751,-2.070422,-2.048163,-2.025966,-2.003464,-1.980071,-1.955746,...,1,A4_A,1959.127856,9.436162,0.719586,2.177710,594.970752,21.460413,0.561526,0.542026
4,-2.425842,-2.383028,-2.340041,-2.299257,-2.262290,-2.229124,-2.197027,-2.164672,-2.132360,-2.098964,...,1,A4_A,1935.468458,10.100680,0.718197,2.230783,503.074855,17.094082,0.595012,0.554225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,-0.376035,-0.374886,-0.373737,-0.374245,-0.378397,-0.384897,-0.392306,-0.398516,-0.404163,-0.408331,...,9,FV6_B,2112.790186,6.789942,0.808732,0.913937,1293.621258,50.138417,0.311599,0.365937
1460,1.553917,1.524941,1.495989,1.463957,1.423202,1.373924,1.325594,1.278005,1.233912,1.190320,...,9,FV6_B,2074.305406,7.207372,0.777162,0.495578,1484.757867,53.714890,0.317394,0.263752
1461,0.040009,0.032494,0.024982,0.015723,0.004007,-0.013167,-0.027390,-0.042244,-0.056658,-0.068830,...,9,FV6_B,2124.786368,7.655965,0.798199,0.547817,1543.429711,60.383956,0.370698,0.278044
1462,-0.423417,-0.430742,-0.438064,-0.447933,-0.461395,-0.478253,-0.495029,-0.510384,-0.524447,-0.535918,...,9,FV6_B,2116.792875,6.798481,0.772055,0.702718,1727.485423,57.100583,0.348527,0.305746
1463,0.277330,0.244050,0.210788,0.170531,0.114999,0.044840,-0.022630,-0.090146,-0.149663,-0.206931,...,9,FV6_B,2116.945336,6.501860,0.792796,0.796407,1534.229705,53.230381,0.350614,0.334210

In [13]:
# Save the dataset
spectral.to_excel('ABCD normally distributed dataset from untreated brick with mortar SNV spectra.xlsx')